### ISSUE TITLE
Memory leak in CloudBlob.DownloadRangeToByteArrayAsync

### ISSUE THREAD

**Issue by PaulDotNet** [Azure/azure-storage-net#221] opened 2015-12-28 04:01 UTC
Library version 6.2.0, running on Windows Phone 8.1 emulator with 1 GB RAM.
After multiple calls to the CloudBlob.DownloadRangeToByteArrayAsync(byte[] target, int index, long? blobOffset, long? length) function throws OutOfMemoryException exception. 
Exception occurs pretty much every time after about 260-300 calls when using 512kb buffer. For test purposes only CloudBlob.DownloadRangeToByteArrayAsync function is called in the loop without any additional allocations or processing.

**Comment by mirobers** [comment] 2015-12-28 22:43
Are you waiting for the tasks to complete? If not, then you may simply be exhausting your memory with too many concurrent operations.

**Comment by PaulDotNet** [comment] 2015-12-28 22:52
There is await. No parallel requests.

**Comment by mirobers** [comment] 2015-12-28 22:58
Thanks. We'll take a look.

**Comment by pemari-msft** [comment] 2016-01-06 00:09
Hi @PaulDotNet ,

Took a look, didn't find anything out of the ordinary. Here's the snippet of what I'm doing, see any differences with yours?:

    CloudBlockBlob blob = cont.GetBlockBlobReference("blob");
    byte[] data = new byte[512 * 1024];
    Random rand = new Random();
    rand.NextBytes(dat);
    await blob.UploadFromByteArrayAsync(dat, 0, 512 * 1024);
    byte[] buf = new byte[512 * 1024];
    for (int i = 0; i < 1000; i++)
    {
        System.Diagnostics.Debug.WriteLine(i);
        await blob.DownloadRangeToByteArrayAsync(buf, 0, 0, 512 * 1024);
    }

All I see when I do memory profiling is a regular allocation/GC cycle and when I run it normally I am able to complete it.

I have seen emulators have issues with memory before (and sometimes even our unit tests fail intermittently) but I have never been able to repro it consistently nor on an actual device. If you have a consistent repro project, would you mind emailing it to `ascl [at] microsoft [dot] com` or could you try to repro yourself on a device to see if it still occurs? 

Thanks!

**Comment by PaulDotNet** [comment] 2016-01-06 00:35
Memory leak is big enough only after several blob (6-7 * 20Mb) downloads. After every download I recreate CloudBlockBlob and allocate the buffer. 
Tried to run profiler to find memory leaks in Visual Studio but it runs out of memory parsing the log file if app downloads more than one blob. 
I'll check if this problem occurs on the phone.

**Comment by pemari-msft** [comment] 2016-01-06 00:37
Okay, sounds like you're doing something pretty different than I understood from your first response. 

Please provide a code snippet so I can make sure I'm doing the same sort of download/upload/allocation and I'll spend some more time investigating.

**Comment by PaulDotNet** [comment] 2016-01-06 00:45
Here is all relevant code. 
```C#
            var storageAccount = CloudStorageAccount.Parse(BlobAccount.Key);
            var blobClient = storageAccount.CreateCloudBlobClient();
            // Retrieve a reference to a container. 
            var container = blobClient.GetContainerReference(containerName);

            var blockBlob = container.GetBlockBlobReference(blobName);
            await blockBlob.FetchAttributesAsync();
            var blobLen = blockBlob.Properties.Length;
            byte[] buffer = new byte[512 * 1024];
            if (progress != null) progress.Report(new ProgressData() { Done = false, ProgressMax = maxFileLength, ProgressValue = 0 });

            using (var fileStream = IsolatedStorageFile.GetUserStoreForApplication().OpenFile(System.IO.Path.Combine(path, blobName) , FileMode.Create))
            {
                long position = 0;
                for (;;)
                {
                    int downloaded = await blockBlob.DownloadRangeToByteArrayAsync(buffer, 0, position, buffer.Length);
                    if (downloaded == 0) break;
                    position += downloaded;
                    await fileStream.WriteAsync(buffer, 0, downloaded);
                    if (progress != null) progress.Report(new ProgressData() { Done = false, ProgressMax = blobLen, ProgressValue = position });
                    if (ct.IsCancellationRequested) return false;
                }
            }
```

**Comment by PaulDotNet** [comment] 2016-01-06 07:42
Here are my experiment results using wp 8.1 emulator with 512MB RAM.
Before blob download app called MemoryManager.ProcessCommittedBytes
After download GC.Collect() and MemoryManager.ProcessCommittedBytes

Blob size 22422037
43 reads of 512kb each
Leak 43642880 bytes (delta of  MemoryManager.ProcessCommittedBytes)
	
Blob size 31864823 
61 reads of 512 kb each
Leak 66084864 bytes

Maybe this info could be helpful.

**Comment by pemari-msft** [comment] 2016-01-07 00:14
`... and then the weirdest thing happened. I left the app on the breakpoint in the debugger for 10 or 20 minutes, then downloaded another blob and voila memory usage decreased from 154222592 to 82518016 bytes.` 

This sounds like slow GC, not a leak. I still am unable to repro with my above code, even running with 2000+ reads. When you say `For the sake of experiment I commented out calls to progress object and writing to the file. Problem reproduced.` Can you clarify the difference between my code and your code? I'm downloading the same blob repeatedly into a buffer and then overwriting the buffer. You say that you're not doing any parallel downloads, but above you say the code snippet `runs once for each blob download.` and that it happens after `6 or 7 downloads`. So these are sequential?

You also say that in one blob of size 22422037 we leak 43642880 bytes (twice the size of the blob)? That doesn't sound like a slow leak that I should have trouble reproing.

Could you please provide a memory analysis of the issue? What do you mean by `Tried to run profiler to find memory leaks in Visual Studio but it runs out of memory parsing the log file if app downloads more than one blob.` ? I have no problems running memory profiler so again there must be something different about our code. Sorry to have to keep going back and forth here. Like I mentioned before, do you have a self contained repro (the above snippet has a bunch of stuff missing from your scenario, and I don't see any difference between yours and mine once you comment out the FileStream and the Progress pieces, so I can't use it as a repro)? That would save us this effort, and if you could zip it and send it to the above email it would be appreciated.

**Comment by PaulDotNet** [comment] 2016-01-07 01:06
After each blob download I invoked GC.Collect().  
I was not downloading the same blob each time. All my blobs were different. Could there be some kind of caching going on?
I'll try to download the same blob multiple times to see if my hypothesis is correct.

Regarding profiler I am not very experienced with it. I just launch Debug->Profiler->start windows phone app analysis and then selected Memory and checked both checkboxes below. 
I'll try to build minimal project later today or tomorrow. This is just my hobby project.

**Comment by PaulDotNet** [comment] 2016-01-07 07:53
I created sample project that leaks but could not send email to the address. When I try to send it I get this back: Your message couldn't be delivered because the group you're sending to needs to know who you are before it will accept your message.
Is there another email that I could use?

**Comment by Cheesebaron** [comment] 2016-01-07 10:02
@PaulDotNet why don't you make a new GitHub repository and chuck it in there?

**Comment by pemari-msft** [comment] 2016-01-07 10:29
I received the project now. Thanks, I'll try again and see what I can dig up.

**Comment by pemari-msft** [comment] 2016-01-08 00:35
Okay, so I took another look. One thing I noticed (and the reason why I was unable to repro) was because I was using a Windows Phone 8.1 project whereas you're using a Windows Phone 8.0 project type. 

I couldn't repro the issue using the Windows Phone 8.1 project type. I see regular GC happening with the same code and no OOM exceptions. Is there any chance that you could update your project to be 8.1 or Windows 10? 

I was however able to see your repro case with your given app (thanks again for sending it). Oddly enough, what I see from the app is just no GC at all. This is why on the third blob download (consistently) we see OOMs. I have no idea why else this might be the case, why the 8.0 project would have this issue but not the 8.1, but I was unable to isolate any piece of our code that would be causing this.

**Comment by pemari-msft** [comment] 2016-01-08 03:35
I also found that by adding thread sleeps before each download I didn't see the OOMs occur.

**Comment by PaulDotNet** [comment] 2016-01-08 17:50
How long thread sleeps did you add? I tried 0.1 - 1 second, before and after download but it is still runs out of memory.
If there is no easy workaround then I guess I'll just add the message. It is good to know that problem occurs only on an old project type.
I intent to migrate my app to windows 10 but I have most of my app users on WP 8 and I would hate to leave them "in the cold" :)

**Comment by pemari-msft** [comment] 2016-01-15 19:42
I added 5 second sleeps. My last ditch question here is whether or not this was a regression. Did you see this with previous versions of the library (4.x or 5.x for example)?

As an aside, I'm surprised to hear that your app users are on WP 8 -- I believe the end of lifecycle support date has passed for WP8 and most libraries are looking to stop supporting it.

**Comment by PaulDotNet** [comment] 2016-01-15 20:12
I guess I'll just ignore this bug for now. Most of my users are on WP8.1 but the project itself is WP8.0 silverlight. I never bothered to migrate it to WP8.1 but W10 looks interesting. 
I have a feeling that the number of pure WP 8.1 apps is pretty low as there was no effortless migration from WP7.1/8 silverlight and benefits of updating were negligible. Maybe it would be more efficient to drop support for 8.1 and keep 8.0 and 10?

**Comment by pemari-msft** [comment] 2016-07-18 22:59
Going to close this for now as I was never able to find a Storage reason for this problem or a workaround we could apply. Please reopen if needed.

**Closed by pemari-msft** 2016-07-18 22:59 UTC
