### ISSUE TITLE
CloudBlockBlob.DownloadToStreamAsync() hangs in some circumstances

### ISSUE THREAD

**Issue by roman-po** [Azure/azure-storage-net#470] opened 2017-06-02 01:03 UTC
My application stores large files in Azure blob containers. The files are sliced and diced into "chunks" with sizes varying between 2MB and 4MB. Each chunk is stored as a separate blob in a blob container.
The application uses CloudBlockBlob.DownloadToStreamAsync(Stream target, CancellationToken cancellationToken) to download the blobs. To increase throughput it downlaods 20 blobs in parallel.

Occasionally a single call to CloudBlockBlob.DownloadToStreamAsync() hangs. It can happen after as few as 100 downloaded blobs, but can also not happen even after thousands of successfully downloaded blobs.

Using Blob container logs and the Azure SDK log I managed to detect a pattern in the logs for those hangs.

For requests that end up hung on the client the Blob container log lists "NetworkError" for request-status and "200" for http-status-code. 
For example : 1.0;2017-05-17T00:06:06.7743648Z;GetBlob;NetworkError;200;23312;106;authenticated;.....

The Azure SDK log shows everything normal for the request up until it lists "Downloading response body." and nothing else for the request. For any request that doesn't hang the log shows more activity, "Processing response body." being the one after "Downloading response body.".

When the request hangs it does not respond to cancellation requests through the provided CancellationToken. Neither it respects the request timeout which is set to 120 sec.

I noticed that the problem is more likely to occur when our network is congested with a lot of traffic to/from Azure due to the testing we do on this application, although each application instance uses a dedicated blob container.

It looks like the server decides to not send the blob data after responding HTTP 200 OK, most likely due to the logged NetworkError. The client however is not aware of that decision and therefore waits for the blob data to arrive.

**Comment by erezvani1529** [comment] 2017-06-02 01:15
Hi @roman-po,

Thanks for you investigation. Which version of the library are you using?  Also when you say request timeout do you mean maximum execution timout?

Please try version 8.1.3 and make sure you are specifying the maximum execution timout on your requests to fix your issue.

Thanks,
Elham

**Comment by roman-po** [comment] 2017-06-02 02:50
Hi Elham,

Thanks for your response.

I had the issue on version 8.1.1 (first observed it on 6.2) and I see that 8.1.3 fixes an issue that perfectly fits what I described. This is a hell of a coincidence. 

The 120 sec timeout I mentioned is set on _CloudBlobClient.DefaultRequestOptions.ServerTimeout_ and from the container logs I saw it being passed on to the server in the request URL, e.g. "https://rpauacc00001.blob.core.windows.net:443/rpauct00005/chunks/b92099eb7fa805043920fcc4100d10282a9cafed48b65142331ebd8e7cf22fa0?timeout=120".

I will take the 8.1.3 right away, but it can take time until I'm confident my issue is resolved. 
Can you give me any tips on how to more reliably reproduce the scenario causing the hang?

If this issue needs to be closed now, I'm OK with it. Alternatively I can wait until all the testing with 8.1.3 is done  and report the result back here.

Thanks,
Roman.

**Comment by erezvani1529** [comment] 2017-06-05 17:07
@roman-po,

Attempting to reproduce might require tampering with network packets mid way through receiving the response and I wont recommend that you spend time on it :) Instead, just make sure you are setting the [MaximumExecutionTime](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.blobrequestoptions.maximumexecutiontime?redirectedfrom=MSDN&view=azure-dotnet#Microsoft_WindowsAzure_Storage_Blob_BlobRequestOptions_MaximumExecutionTime) on the [BlobRequestOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.blob.blobrequestoptions?view=azure-dotnet) and run your regular traffic. We can close this issue for now however please do not hesitate to re-open if you see any problems or have related questions.

Thanks,
Elham

**Closed by erezvani1529** 2017-06-05 17:07 UTC

**Comment by MatanEdri** [comment] 2017-06-13 12:10
Hi, 

I have the same issue in 8.1.4 when trying to the stream the blob contents using CloudBlockBlob.OpenReadAsync().

Can this issue be reopened?

**Comment by erezvani1529** [comment] 2017-06-13 20:11
Hi @MatanEdri,

Since this stack is not same as the one for which we fixed the issue, I would like to check whether you are specifying the maximum execution time on the request options for your requests? this will help identify whether this is an actual hang (please go ahead and share the dumps on the email-thread you have started as well).

Thanks, 
Elham

**Comment by Plasma** [comment] 2018-07-18 22:53
@erezvani1529 @MatanEdri I've got the same intermittent issue (worker role, exact same stack trace).

Is there a problem if a caller calls OpenReadAsync() but then later reads the stream synchronously via Read()?

**Comment by Plasma** [comment] 2019-01-28 09:05
I'm suspicious of this happening still; anyone from Storage team able to provide any insight?

**Comment by Plasma** [comment] 2019-01-28 09:05
... also as @loic-sharma has a reproduction it would be wonderful if you are able to package that up as an example project to demonstrate the bug
