### ISSUE TITLE
(400) Bad Request - The specified block list is invalid. ErrorCode:InvalidBlockList

### ISSUE THREAD

**Issue by mebjas** [Azure/azure-storage-net#780] opened 2018-10-02 11:38 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
WindowsAzure.Storage `6.2.0`

### Which platform are you using? (ex: .NET Core 2.1)
.Net Framework 4.5.1

### What problem was encountered?
Getting this 400 Bad Request with message in transient fashion randomly.
```
The specified block list is invalid. 
```

ErrorCode: **InvalidBlockList**

API being used:
```c#
public virtual void UploadFromByteArray(byte[] buffer, int index, int count, AccessCondition accessCondition = null, BlobRequestOptions options = null, OperationContext operationContext = null);
```

### How can we reproduce the problem in the simplest way?
Execute this scenario and run multiple times with different threads uploading together 100MB or so type of data.

### Have you found a mitigation/solution?
Not Yet

**Comment by mebjas** [comment] 2018-10-08 13:16
No updates? @erezvani1529

**Comment by alexmbaker** [comment] 2019-02-18 08:02
I am encountering a similar issue, I am uploading a large number of files to block blobs and find an exception is thrown once every minute or two.  

- Files do not exist in the storage account (so this is not an overwrite of an existing file)
- Files are typical user documents ranging in size from 200KB to 10MB
- The issue occurs when there is only one client application using the container in the storage account


## Environment

- .NET 4.6.1 Console Application
- Microsoft.Azure.Storage.Blob / Microsoft.Azure.Storage.Blob  v9.4.2.0 

## The code 

Nothing clever here however it is possible that the sourceStream is not seekable which may cause a slightly different code path to be followed in the SDK

``` C#
public void UploadStream(string filePath, Stream sourceStream, FileSaveMode fileSaveMode) {
 CloudBlockBlob blockBlobReference = this.GetContainer().GetBlockBlobReference(this.GetBlobName(filePath));
        AccessCondition uploadAccessCondition = this.GetUploadAccessCondition(fileSaveMode);
        blockBlobReference.Properties.ContentType = MimeMapping.GetMimeMapping(filePath);
        blockBlobReference.UploadFromStream(sourceStream, uploadAccessCondition, null,  null);
}
```
Exception Stack Trace
```
Microsoft.WindowsAzure.Storage.StorageException: The specified block list is invalid.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Core\Executor\Executor.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.<CommitAsync>d__20.MoveNext() in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 412
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Blob.BlobWriteStream.Commit() in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\BlobWriteStream.cs:line 341
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStreamHelper(Stream source, Nullable`1 length, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 406
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.UploadFromStream(Stream source, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext) in C:\Program Files (x86)\Jenkins\workspace\dotnet-split-pr-master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 272

Request Information
RequestID:762d2c35-6f22-4401-9853-2ac23ed9104a
RequestDate:Mon, 18 Feb 2019 15:18:53 GMT
StatusMessage:The specified block list is invalid.
ErrorCode:InvalidBlockList
ErrorMessage:The specified block list is invalid.
RequestId:762d2c35-6f22-4401-9853-2ac23ed9104a
Time:2019-02-18T04:18:53.6619373Z

```

**Comment by alexmbaker** [comment] 2019-03-01 05:59
I have a feeling that this issue may be caused by two tasks writing to the same blob at the same time..

**Comment by prapanw** [comment] 2019-07-15 23:24
Yes, I got the same error when there were two jobs trying to write to the same blob.

**Comment by kfarmer-msft** [comment] 2019-08-06 18:17
We also saw this in testing.  I was able to affect it internally by adding a wait between the upload of the blocks and the committing of the block list IDs, but imposing delays is not really a solution.

I've reported this to the server folks on their request.  Obviously someone is prematurely signalling that they're done with an upload, but it's unclear if it's the server, the OS's http stack, the HttpClient class, or the client library.

**Comment by mattgaspar** [comment] 2019-08-14 01:40
I was also encountering this error with the Nodejs Azure library.  It turned out to be multiple concurrent uploads of the same blob (they were from emails containing duplicate embedded images - signatures of replies).

Can you please come up with a better error code and message for this issue instead of InvalidBlockList?  It should be something like BlobLocked or WriteInProgress

**Comment by ugumba** [comment] 2019-09-08 13:55
We're hit by this using Microsoft.Azure.Storage.Blob 11.0.0.  Unlike many of the other reporters, there's no possibility of concurrent uploads to the same blobs!  
Our blobs (~300 KB each) are computed by AKS pods (~10 seconds each), then uploaded via OpenWriteAsync and CopyToAsync to uniquely named blobs.  We've verified with Jaeger, logs and common sense that there are no duplicates.  
Roughly 1 in 10 fail with "The specified block is invalid".  It seems to us like there is a problem either in the client library or at the receiving end.  We will probably have to catch and retry, but this will waste significant resources.

**Comment by sfergusonATX** [comment] 2020-01-27 01:51
I'm also encountering this error in a production application, in much the same way @ugumba described it. It's not a concurrency issue; it happens during a scheduled job that runs once a day. I'm seeing it pop up in about once in every 15 attempts. It seems like it's more likely to occur if the file size is large (the last failure I had was on a file that was 200mb).

Service: Blob
SDK: Microsoft.WindowsAzure.Storage, Version=9.3.2.0
Platform: .NET Core 2.2
Problem: The specified block list is invalid.
API: public virtual Task<CloudBlobStream> OpenWriteAsync();

**Comment by ddobric** [comment] 2020-03-21 10:56
Anything new regarding this?

![image](https://user-images.githubusercontent.com/1756871/77224958-dc014e80-6b6a-11ea-8b0f-bec553bbacfa.png)

 <PackageReference Include="Microsoft.Azure.Storage.Blob" Version="11.1.3" />

**Comment by superyyrrzz** [comment] 2020-04-22 15:34
Same issue here. We have logic to ensure there is no concurrent write to the same blob. Any update?

**Comment by HengzheLi** [comment] 2020-06-23 09:22
Same as @ugumba. Any update about this issue? I am using SDK v11.

**Comment by himanshubillore** [comment] 2020-06-26 12:22
Any updates? I am getting same error for upload of large size, say more than 80GB. My Blob Name is properly incremented, so it is not because of uploading to same blob, as others are reporting.

**Comment by georgelivingston** [comment] 2020-09-25 13:44
Facing the same problem in the below SDK version. Any solution to overcome?

Microsoft.Azure.Storage.Blob (11.1.0) from UploadFromStreamAsync

**Comment by jlim1545** [comment] 2020-10-20 21:36
Facing the same problem in the Golang SDK as well.

**Comment by himanshubillore** [comment] 2020-10-23 11:55
> Facing the same problem in the Golang SDK as well. Any solution to overcome?

I could fix it in my code itself. I was generating the same blob number for the next blob also. That was wrong. All blocks should be uploaded to a blob and then committed to the same blob. For me even the 2nd set of blocks were uploaded and committed to the 1st blob only.
Suggest you to print the URLs of all the PUT operations, and see what is the blob-id in them.

**Comment by angelcalvasp** [comment] 2020-10-28 20:45
Facing this issue in a non concurrent manner
using the following code

``` csharp
using (var writer = await blob.OpenWriteAsync())
using (var streamWriter = new StreamWriter(writer))
using (var csvWriter = new CsvWriter(streamWriter))
{
         csvWriter.WriteRecords(rows);
}
```

using library version 11.1.7
<PackageReference Include="Microsoft.Azure.Storage.Blob" Version="11.1.7" />

Any route I can take without changing to the new version?

**Comment by moroz-slavomir** [comment] 2020-12-08 18:35
We are also facing the same issue and have done a little bit of an investigation in the application insights. Here is what we have found. 

### Trivia
The `Put Block` operation creates a new block to be committed as part of a blob.
![image](https://user-images.githubusercontent.com/14807331/101523128-7703b800-3988-11eb-859a-f8a3b9075105.png)

The `Put Block` List operation writes a blob by specifying the list of block IDs that make up the blob. In order to be written as part of a blob, a block must have been successfully written to the server in a prior Put Block operation.
![image](https://user-images.githubusercontent.com/14807331/101523247-a286a280-3988-11eb-9ce9-403b4aedb25b.png)

### Successful upload
Consists of 1-n `Put Block` operations and final `Put Block List` operation.
![image](https://user-images.githubusercontent.com/14807331/101523319-bc27ea00-3988-11eb-8763-6389a08fa4eb.png)

### Failed upload
In the failed upload the final `Put Block List` fails with message `The specified block list is invalid.`
![image](https://user-images.githubusercontent.com/14807331/101524961-ed091e80-398a-11eb-8ba3-bca7b8cfc468.png)

### Possible cause
It seems that storage SDK is executing the `Put Block List` in parallel with the `Put Block` and does not wait for the `Put Block` to finish. 

**Successful upload timeline**
Upload #1 - 1 block
![image](https://user-images.githubusercontent.com/14807331/101523547-090bc080-3989-11eb-9d15-417cd86afce5.png)
2020-12-07T12:53:09.8442922Z + 0.01
2020-12-07T12:53:09.854617Z

Upload #2 - many blocks
![image](https://user-images.githubusercontent.com/14807331/101523749-4a9c6b80-3989-11eb-9e2f-d08ded198df1.png)
2020-12-07T13:17:51.3556283Z + 0.371
2020-12-07T13:17:51.7276951Z

**Failed upload timeline**
Upload #3 - 2 blocks
![image](https://user-images.githubusercontent.com/14807331/101524573-66544180-398a-11eb-877a-beb12ff38a58.png)
2020-11-27T13:27:44.3833279Z + 0.03
2020-11-27T13:27:44.3835717Z

Upload #4 - 2 blocks
![image](https://user-images.githubusercontent.com/14807331/101524705-90a5ff00-398a-11eb-9e9f-22e1fefa2d8b.png)
2020-11-27T13:38:11.1370163Z + 0.105
2020-11-27T13:38:11.1372083Z

We are also using `OpenWriteAsync()` as was @angelcalvasp in his example, so my guess is that the problem lies in the `BlobWriteStream`. 

`CommitAsync` is calling `PutBlockListAsync` (the final operation) and before that it runs `FlushAsync`. It [appears](https://github.com/Azure/azure-storage-net/blob/b0d47bfd4c1c0dcbe60eaf373e2977cd7405aa5f/Lib/WindowsRuntime/Blob/BlobWriteStream.cs#L192) the the `FlushAsync` should block until all pending block writes are finished, but I guess it doesn’t work properly.

**Comment by amishra-dev** [comment] 2020-12-08 22:34
@seanmcc-msft / @amnguye can you please look at this.

**Comment by amishra-dev** [comment] 2020-12-08 22:42
@moroz-slavomir 
Hi Salvomir,
Can you please share which version of the SDK you tried this with?

**Comment by moroz-slavomir** [comment] 2020-12-09 00:18
Sure. Here you go.
Version: 11.2.2
Platform: .Net Framework 4.7.2

**Comment by tomasdeml** [comment] 2021-02-23 11:48
What is the status of the issue? We are also experiencing random `InvalidBlockList` responses in production (.NET Core v3.1.7 (fcfdef8d6b), SDK v11.2.2) 😢.

Is there any known workaround or should we just upgrade to v12?

**Comment by immarvin** [comment] 2021-02-27 01:02
Hi,

This issue is intermittently breaking the upload availability in our service.  Since V12 includes lots of breaking changes, which will cost explicit time and effort to complete the upgrade, due to the emergency of this issue and our development schedule, upgrading to V12 is not an option as the fix of this issue.
 
According to the business announcement on https://github.com/Azure/azure-storage-net, 
**•  We will be making only fixes related data integrity and security for 11.x.**
•  We will not be adding new storage service version support for this SDK.
•  We will not be back porting fixes and features added to the current version to the versions in this repo
•  We will not be making any changes to the performance characteristics of this SDK.
 
**Apparently, this issue falls into the category of “related data integrity and security for 11.x”, it should be fixed in V11.**

According to https://docs.microsoft.com/en-us/dotnet/api/overview/azure/storage?view=azure-dotnet, the V11 .net SDK is not out of support:

> If you cannot update existing applications to version 12.x, then Microsoft recommends using version 11.x.


I will request a fix on this through the support channel of Azure blob storage service

**Comment by IvanRazor** [comment] 2021-03-26 14:33
Hi there,

is there any update for this issue?
We also facing this problem using "Task UploadFromStreamAsync(Stream source);".
We using Microsoft.Azure.Storage.Blob, Version=**11.2.2.0** and .NET Core 3.1.
No concurrency in our case.

As I understood from this topic, there are 3 ideas, how to fix it:

1. Retry pattern
2. Update the library to v.12.x may help (is this problem already fixed in the v 12.x ?)
3. @immarvin wanted to request a fix for version 11.x (could you share info, if you have any update)

**Comment by immarvin** [comment] 2021-03-29 05:06
Hey guys,

I opened a ticket to azure support, it cost me a lot of time to collect the client side information, but got no valid progress after lots of mails back and forth, I reminded them the root cause analysis in this ticket at least three times, the support guys did not get the point that this is a sdk issue, the azure support chain is so long that it seems quite difficult to esculate this issue to the develop team. 

I am in such a deadlock: support guys asked me to provide lots of client side logs, I provided, then feedback with the possible analysis on failed requests which is not related to SDK, then asked for latest client side logs, I realized it is just wasting time but still collected the information and provided, then support guys returned me the possible server side information on the failed requests, then... 

@seanmcc-msft ,is it possible that the SDK development team take a look at the root cause analysis on https://github.com/Azure/azure-storage-net/issues/780#issuecomment-740826850 ?

**Comment by kasobol-msft** [comment] 2021-04-13 21:07
To provide update. I was able to establish a repro here https://github.com/kasobol-msft/azure-storage-net/commit/32f243196be7fc013e02da7e2f895ae32d848700 .
And it seems that the culprit is in this line:
https://github.com/Azure/azure-storage-net/blob/b0d47bfd4c1c0dcbe60eaf373e2977cd7405aa5f/Lib/Common/Core/Util/AsyncExtensions.Common.cs#L232
I.e. the task scheduled in constructor may complete later and unlock the `AsyncManualResetEvent` in the middle of writting to stream.

We'll be working on the fix.

Here's sample run where this repro'ed:
![image](https://user-images.githubusercontent.com/61715331/114621440-8dd15880-9c61-11eb-881e-92bf35f611ef.png)

**Comment by immarvin** [comment] 2021-04-14 02:42
@kasobol-msft , great. Thanks a lot and cannot wait for the fix be released.

**Comment by kasobol-msft** [comment] 2021-04-15 06:07
I have found couple of other places with race condition. See https://github.com/kasobol-msft/azure-storage-net/commit/7df5f741eb9b74a10c94f98ece93082b6b89aee4 for reference.
Good news is that the draft of the fix has run for several hours without an issue (all these races were failing test runs within minutes). We'll be working on shipping that fix.

**Comment by kasobol-msft** [comment] 2021-04-15 17:50
The fix is available on Nuget. Version `11.2.3`.

**Closed by kasobol-msft** 2021-04-15 17:50 UTC
Labels: investigate

**Comment by jeffhli** [comment] 2021-05-07 04:14
After upgrade to 11.2.3, we are still suffering from this issue.

**Comment by immarvin** [comment] 2021-05-07 04:22
the exception trace:
```
Microsoft.Azure.Storage.StorageException: The specified block list is invalid.\n   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)\n   at Microsoft.Azure.Storage.Blob.BlobWriteStream.CommitAsync()\n   at Microsoft.Azure.Storage.Blob.BlobWriteStream.Dispose(Boolean disposing)\n   at System.IO.Stream.Close()\n   at System.Security.Cryptography.CryptoStream.Dispose(Boolean disposing)\n   at System.IO.Stream.Close()\n   at Microsoft.Azure.Storage.Blob.BlobEncryptedWriteStream.Dispose(Boolean disposing)\n   at System.IO.Stream.Close()\n   at Seismic.Platform.BlobStorage.AzureBlobStorage.AzureBlobEntity.UploadFromStream(Stream source, OperationContext ctx, CancellationToken token)\nRequest Information\nRequestID:cc9626dc-e01e-0065-5fdd-426804000000\nRequestDate:Fri, 07 May 2021 01:08:52 GMT\nStatusMessage:The specified block list is invalid.\nErrorCode:InvalidBlockList\nErrorMessage:The specified block list is invalid.\nRequestId:cc9626dc-e01e-0065-5fdd-426804000000\nTime:2021-05-07T01:08:52.8324848Z\n\n   --- End of inner exception stack trace ---\n   at
```

**Comment by kasobol-msft** [comment] 2021-05-07 05:15
By looking at stack trace it seems that you're using client side encryption and `UploadFromStream` which ends up hitting this code:
https://github.com/Azure/azure-storage-net/blob/fcbd5453908d188ab54d75abc2cb6c5f2c43ddfa/Lib/ClassLibraryCommon/Blob/CloudBlockBlob.cs#L412-L417

This particular case wasn't well represented in my repro, so there might be some extra race condition be hidden there. I'll try to modify repro to account for that case.
Most likely the race is between ` blobStream.Commit();` and disposal triggered by `using` OR `Commit` from `BlobEncryptedWriteStream` has a bug.

Meanwhile I suggest to try using openwrite directly without that extra commit, i.e. something like this:
https://github.com/kasobol-msft/azure-storage-net/blob/7df5f741eb9b74a10c94f98ece93082b6b89aee4/TestApp1/Program.cs#L116-L120
That option didn't give me a single repro in hours long stress test.

**Comment by immarvin** [comment] 2021-05-07 05:27
@kasobol-msft , thanks for your information, yes we are using client side encryption. Looking forward for your fix and we will try the workaround as you suggested. 

thanks a lot

**Comment by kasobol-msft** [comment] 2021-05-07 06:04
@immarvin  Could you share what `Seismic.Platform.BlobStorage.AzureBlobStorage.AzureBlobEntity.UploadFromStream` does ? It seems to use open write directly. Looks like I confused it with `CloudBlockBlob.UploadFromStream`.

**Comment by immarvin** [comment] 2021-05-07 07:56
fyi @kasobol-msft 
```
        public async Task UploadFromStream(Stream source, OperationContext ctx, CancellationToken token)
        {
            ...
            try
            {
                var options = downloadRoute.GetBlobRequestOptions(storageOptions.KeyResolver, storageOptions.Key);
                if (source.CanSeek)
                {
                    await cloudBlob.UploadFromStreamAsync(source, null, options, ctx, token).ConfigureAwait(false);
                    blobSize = source.Position;
                }
                else
                {
                    byte[] buffer = new byte[256 * 1024];
                    int read;
                    blobSize = 0;
                    using (CloudBlobStream targetStream = (cloudBlob as CloudBlockBlob).OpenWrite(null, options))
                    {
                        while ((read = source.Read(buffer, 0, buffer.Length)) > 0)
                        {
                            targetStream.Write(buffer, 0, read);
                            blobSize += read;
                        }
                    }
                }
            }
            catch ...
    }
```

**Comment by kasobol-msft** [comment] 2021-05-07 19:06
@immarvin I haven't had much luck with repro so far. Could you share the following details?
- What's encryption policy you're using? If that's something custom or you can't disclose then I'm trying to figure out which branch [here](https://referencesource.microsoft.com/#mscorlib/system/security/cryptography/cryptostream.cs,544) does it go, i.e. weather 'ICryptoTransform` you're using `CanTransformMultipleBlocks` and what's the size of `InputBlockSize` and `OutputBlockSize`. Also what's the ratio of encrypted to unencrypted data size?
- Do you configure `CloudBlockBlob.StreamWriteSizeInBytes` property ?
- What's the size range of `Stream source` that you have in your system ?
- Which .NET runtime do you use? (Net Framework, Net Core, which version?)
- What operating systems is that running on?
- What's the origin of `Stream source`? i.e. is it file stream, network stream or some custom stream that produces data on the fly?
- What's typical latency of upload/write operation?

**Comment by jeffhli** [comment] 2021-05-10 04:26
@kasobol-msft 
1. ```/// <returns></returns>
        public virtual BlobRequestOptions GetBlobRequestOptions(IKeyResolver keyResolver = null, IKey key = null, TimeSpan? maximumExecutionTime = null)
        {
            BlobRequestOptions result = new BlobRequestOptions
            {
                RetryPolicy = new ExponentialRetry(TimeSpan.FromSeconds(1), 5),
                MaximumExecutionTime = maximumExecutionTime ?? TimeSpan.FromHours(1),
                LocationMode = Location
            };
            if (keyResolver != null || key != null)
            {
                result.EncryptionPolicy = new BlobEncryptionPolicy(key, keyResolver);
            }
            return result;
        }
2. We don't configure the  `CloudBlockBlob.StreamWriteSizeInBytes` property.
3. The size range 0~10485700 can reproduce this issue sometimes.
4. .Net Runtime is Net Core3.1
5. We are running in docker `mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim` OS: Debian 10
6. `Stream source` is network stream
7. Not sure the latency of upload/write operation.
8. Refer to the item 1

**Comment by kasobol-msft** [comment] 2021-05-14 16:17
@immarvin @jeffhli 
I didn't have much luck reproducing this. I'd like to request further details.

1. What's `IKeyResolver` or `IKey` implementeation you're using?

2. It might help if you could run a repro on your side with additional logging enabled and share log generated when issue occurs. I'm wondering if you're running into case where put block failed for some reason, got retired (or not) and that messed up something in the process. Could you please add something like this to your program (this will help understand sequence of events better)?

```
OperationContext operationContext = new OperationContext();
operationContext.SendingRequest += (object sender, RequestEventArgs e) =>
                    Console.WriteLine($"{DateTime.UtcNow:O} SendingRequest x-ms-client-request-id={e.Request.Headers.GetValues("x-ms-client-request-id").FirstOrDefault()}");
operationContext.ResponseReceived += (object sender, RequestEventArgs e) =>
                    Console.WriteLine($"{DateTime.UtcNow:O} ResponseReceived status={e.Response.StatusCode} x-ms-client-request-id={e.Request.Headers.GetValues("x-ms-client-request-id").FirstOrDefault()} activity-id={e.Response.Headers.GetValues("x-ms-request-id").FirstOrDefault()}");
operationContext.Retrying += (object sender, RequestEventArgs e) =>
                    Console.WriteLine($"{DateTime.UtcNow:O} Retrying status={e.Response?.StatusCode} x-ms-client-request-id={e.Request.Headers.GetValues("x-ms-client-request-id").FirstOrDefault()} activity-id={e.Response?.Headers.GetValues("x-ms-request-id").FirstOrDefault()}");
operationContext.RequestCompleted += (object sender, RequestEventArgs e) =>
                    Console.WriteLine($"{DateTime.UtcNow:O} ResponseReceived status={e.Response.StatusCode} x-ms-client-request-id={e.Request.Headers.GetValues("x-ms-client-request-id").FirstOrDefault()} activity-id={e.Response.Headers.GetValues("x-ms-request-id").FirstOrDefault()}");


using (CloudBlobStream targetStream = (cloudBlob as CloudBlockBlob).OpenWrite(null, options, operationContext))
{
     while ((read = source.Read(buffer, 0, buffer.Length)) > 0)
     {
        targetStream.Write(buffer, 0, read);
        blobSize += read;
     }
}
```
