### ISSUE TITLE
Storage calls are hanging on Centos 7.2.

### ISSUE THREAD

**Issue by serkantkaraca** [Azure/azure-storage-net#347] opened 2016-09-28 00:58 UTC
Hello,

I am from Azure EventHubs team and working on our NetCore client. We have hit an issue with storage calls during stress testing of our client on Centos 7.2 VMs. All storage calls seem to be getting into stuck state after running many hours. In order to reproduce this issue more often I have decided to increase the rate of calls to storage and this seems to have helped. Now I can see the client calls are getting stuck in minutes. Please note that, this issue doesn't repro on our Windows runs.

In order to simplify the repro, I have implemented a standalone app as below. This repro demonstrates the issue on CloudBlockBlob.DownloadTextAsync() calls. Let me know if you have any questions. 
[StorageRepro.zip](https://github.com/Azure/azure-storage-net/files/496923/StorageRepro.zip)

Thanks

**Comment by erezvani1529** [comment] 2016-09-28 17:57
Hi @serkantkaraca,

Thank you for reporting this issue. We will investigate and update with our findings.

Thanks!

**Comment by serkantkaraca** [comment] 2016-09-28 20:46
I will shortly try the repro on Debian and Ubuntu to see if this is a Centos only issue. I will update the thread today.

**Comment by serkantkaraca** [comment] 2016-09-28 23:12
Tried the repro this on 5 different Centos boxes and all got stuck at some different times. Debian and Ubuntu clients are still running fine.

**Comment by rambo-msft** [comment] 2016-09-29 00:06
Interesting -- thanks for confirming that for us.

**Comment by serkantkaraca** [comment] 2016-10-05 17:12
Any updates?

**Comment by rambo-msft** [comment] 2016-10-10 17:15
Hi @serkantkaraca,
Strangely enough, we haven't been able to repro this issue. We also tested on RHLE, but it's likey this problem may hinge on CoreCLR running on a specific version of Centos. I will try it out with some other vhds just to be sure.

**Comment by serkantkaraca** [comment] 2016-10-10 17:32
Here is the vesioning information of VMs I am using.

[stressuser@stresslinux301 ~]$ cat /etc/centos-release
**CentOS Linux release 7.2.1511 (Core)**
[stressuser@stresslinux301 ~]$ uname -a
**Linux stresslinux301 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux**
[stressuser@stresslinux301 ~]$

**Comment by serkantkaraca** [comment] 2016-10-21 23:06
Ayn updates?

**Comment by serkantkaraca** [comment] 2016-11-03 16:40
We have identified same issue on MacOS.

**Comment by erezvani1529** [comment] 2016-11-03 17:09
Hi @serkantkaraca,

Apologies about the delay in response and thanks for the information regarding the MacOS repro.

We are trying to repro again with the image information you have shared and follow up with CoreCLR team to identify the root cause(as mentioned before, the image we used did not lead to a repro).

Thanks!

**Comment by serkantkaraca** [comment] 2016-11-03 17:14
Please ping me from serkar@Microsoft. I will provide you a VM that you can repro.

**Comment by serkantkaraca** [comment] 2017-02-13 23:10
Any updates?

**Comment by erezvani1529** [comment] 2017-03-06 21:07
Hi @serkantkaraca,

Closing this issue as per our offline discussion. This issue is not happening any more with NetCore1.1.


Thanks,
Elham

**Closed** 2017-03-06 21:07 UTC
