### ISSUE TITLE
CopyToAsync from blob read stream to blob write stream gets stuck

### ISSUE THREAD

**Issue by johnthcall** [Azure/azure-storage-net#866] opened 2019-03-21 16:59 UTC
### Which service(blob, file, queue, table) does this issue concern?
Blob

### Which version of the SDK was used?
9.4.2

### Which platform are you using? (ex: .NET Core 2.1)
.Net Framework 4.7.2

### What problem was encountered?
Copying a Blob OpenReadAsync stream into a blob OpenWriteAsync stream using Stream.CopyToAsync will sometimes get stuck and will never proceed, we have seen it get stuck for up to 9 hours before we restarted the process.

### How can we reproduce the problem in the simplest way?
Make ~800 blob files with a size of ~9 MB. Open a single write stream to a blob and copyToAsync all of the 800 blobs sequentially. We do not have a consistent repro but it does happen about once every 90 attempts.

### Have you found a mitigation/solution?
Killing the process causes the same work to be done successfully. We will be adding a timeout to resolve automatically but would like the underlying issue fixed.

We have a dump and mini-dump but they contain prod secrets and would prefer to share them internally.

Seems similar to #775 but not on an emulator.

**Comment by markheath** [comment] 2019-07-25 08:23
We've seen this a lot recently (both with the old 9.3.3 and current SDKs). We weren't able to track down what the root cause was, but where possible we've switched all blob copying to use `StartCopyAsync` instead.

**Comment by Plasma** [comment] 2019-08-08 07:03
Hi @markheath and @johnthcall 

I was the original poster about the storage emulator issue; but I think we've spotted this happening in production also. May know if theres a potential fix overnight.

In my code review there is a lot of moving parts/complexity when using the Azure storage read/write streams. A lot of thread pooling/blocking behind the scenes that is probably hiding some subtle bug like we are discussing that causes deadlocks.

**Comment by kasobol-msft** [comment] 2020-04-30 22:57
Fixed in 11.1.4 version
PR: #985

**Closed by kasobol-msft** 2020-04-30 22:57 UTC
Labels: investigate
