### ISSUE TITLE
WindowsAzure.Storage 4.3.0 error: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral

### ISSUE THREAD

**Issue by dcinzona** [Azure/azure-storage-net#125] opened 2015-04-29 13:20 UTC
We have a web app running on Orchard CMS that communicates with Azure.  Running the app locally, in IIS or within visual studio produces the error.  Also, deploying to Azure produces the error as well.
We have Microsoft OData version 5.6.3 installed and Orchard uses that same version.

We are using OData version 5.6.3 and we are getting the error below.  I have verified that the DLL is in the bin directory and web.config

Any idea why/if there is a hard reference to 5.6.2?  The Nuget package states it can use >= 5.6.2

Our config:
```xml
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.0.0" newVersion="4.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Services.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>
```

    Microsoft.WindowsAzure.Storage.StorageException: Could not load file or assembly
    'Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
    or one of its dependencies. The located assembly's manifest definition does not match the assembly
    reference. (Exception from HRESULT: 0x80131040) ---> 
    System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Data.OData, Version=5.6.2.0,
    Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
    The located assembly's manifest definition does not match the assembly reference. 
    (Exception from HRESULT: 0x80131040) 
    at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpWebRequestFactory.BuildRequestForTableOperation(Uri uri, UriQueryBuilder builder, IBufferManager bufferManager, Nullable`1 timeout, TableOperation operation, Boolean useVersionHeader, OperationContext ctx, TablePayloadFormat payloadFormat, String accountName)
    at Microsoft.WindowsAzure.Storage.Table.TableOperation.<>c__DisplayClass18.<RetrieveImpl>b__15(Uri uri, UriQueryBuilder builder, Nullable`1 timeout, Boolean useVersionHeader, OperationContext ctx)
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ProcessStartOfRequest[T](ExecutionState`1 executionState, String startLogMessage)
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
    --- End of inner exception stack trace ---
    at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
    at Microsoft.WindowsAzure.Storage.Table.CloudTable.Exists(Boolean primaryOnly, TableRequestOptions requestOptions, OperationContext operationContext)
    at Microsoft.WindowsAzure.Storage.Table.CloudTable.CreateIfNotExists(TableRequestOptions requestOptions, OperationContext operationContext)

**Comment by pemari-msft** [comment] 2015-04-30 20:39
This sounds like an assembly loading issue. Perhaps your web.config is not taking effect? Could you please try using Fuslogvw.exe ( https://msdn.microsoft.com/en-us/library/e74a18c4.aspx ) to check? Binding redirects should solve this problem, like you mentioned. Thanks!

**Comment by dcinzona** [comment] 2015-05-01 19:25
This is what I get in the logs:

```
*** Assembly Binder Log Entry  (5/1/2015 @ 3:20:21 PM) ***

The operation failed.
Bind result: hr = 0x80131040. No description available.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  c:\windows\system32\inetsrv\w3wp.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/WWW/orchard 1.9-int/
LOG: Initial PrivatePath = C:\WWW\orchard 1.9-int\bin
LOG: Dynamic Base = C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\aa2320a0
LOG: Cache Base = C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\aa2320a0
LOG: AppName = 6d3135d0
Calling assembly : Microsoft.WindowsAzure.Storage, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\WWW\orchard 1.9-int\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/root/aa2320a0/6d3135d0/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/root/aa2320a0/6d3135d0/Microsoft.Data.OData/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL file:///C:/WWW/orchard 1.9-int/bin/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL file:///C:/WWW/orchard 1.9-int/bin/Microsoft.Data.OData/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL file:///C:/WWW/orchard 1.9-int/App_Data/Dependencies/Microsoft.Data.OData.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\WWW\orchard 1.9-int\App_Data\Dependencies\Microsoft.Data.OData.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: Microsoft.Data.OData, Version=5.6.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

*** Assembly Binder Log Entry  (5/1/2015 @ 3:20:21 PM) ***

The operation failed.
Bind result: hr = 0x80131040. No description available.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  c:\windows\system32\inetsrv\w3wp.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/WWW/orchard 1.9-int/
LOG: Initial PrivatePath = C:\WWW\orchard 1.9-int\bin
LOG: Dynamic Base = C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\aa2320a0
LOG: Cache Base = C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\aa2320a0
LOG: AppName = 6d3135d0
Calling assembly : Microsoft.WindowsAzure.Storage, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\WWW\orchard 1.9-int\web.config
LOG: Using host configuration file: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\aspnet.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Data.OData, Version=5.6.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/root/aa2320a0/6d3135d0/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/Temporary ASP.NET Files/root/aa2320a0/6d3135d0/Microsoft.Data.OData/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL file:///C:/WWW/orchard 1.9-int/bin/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL file:///C:/WWW/orchard 1.9-int/bin/Microsoft.Data.OData/Microsoft.Data.OData.DLL.
LOG: Attempting download of new URL file:///C:/WWW/orchard 1.9-int/App_Data/Dependencies/Microsoft.Data.OData.DLL.
LOG: Assembly download was successful. Attempting setup of file: C:\WWW\orchard 1.9-int\App_Data\Dependencies\Microsoft.Data.OData.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: Microsoft.Data.OData, Version=5.6.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
WRN: Comparing the assembly name resulted in the mismatch: Build Number
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

**Comment by sozler-msft** [comment] 2015-05-01 21:20
So, yes, it looks like it was able to find 5.6.3, but could not match it with 5.6.2. That means the assembly binding redirect is not taking effect, so we should look for errors. How does the `assemblyBinding` tag look like in your web.config?

**Comment by dcinzona** [comment] 2015-05-01 21:48
This is in the web.config

```xml

      <dependentAssembly>
        <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.3.0.0" newVersion="4.3.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Edm" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.Services.Client" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.OData" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.6.3.0" newVersion="5.6.3.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="Autofac" publicKeyToken="17863af14b0044da" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-3.5.0.0" newVersion="3.5.0.0" />
      </dependentAssembly>
```

**Comment by sozler-msft** [comment] 2015-05-01 21:49
Does `assemblyBinding` has the correct `xmlns` attribute?

**Comment by dcinzona** [comment] 2015-05-01 21:58
I'm not sure I understand...
I think I got this worked out though.  Our project is running on Orchard, and the module that was accessing AzureStorage had the bindings in the config, but the main web application did not.
I added those bindings to the root web.config and it seems to have resolved the issue!
Referenced here: https://github.com/OrchardCMS/Orchard/issues/5187

**Comment by sozler-msft** [comment] 2015-05-01 21:59
Great! I'm glad you found the root cause. I will go ahead and close the issue then.

**Closed by sozler-msft** 2015-05-01 21:59 UTC

**Comment by dcinzona** [comment] 2015-05-01 22:01
Thanks for pointing me in the right direction!  I would have never figured this out without fuslogvw :+1:

**Comment by oviwankenobi** [comment] 2016-03-31 16:58
hi there, I a very similar problem which I [described it here](http://stackoverflow.com/questions/36331296/could-not-load-file-or-assembly-microsoft-data-odata-version-5-6-4-0-culture)

I have the error "could not load 'Microsoft.Data.OData, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies."

I have all the binding redirects in place to version 5.7.0.0, however at run time the azure instance can not find the Microsoft.Data.OData, Version=5.6.4.0!

I was able to RDP to the instance and look with .net reflector, and loading my service dll from azure instance (E:\approot\bin), it seems I have two assemblies depending on this Microsoft.Data.Edm, Version=5.6.4.0: one is Microsoft.Azure.Storage.dll and the other is Microsoft.Data.OData.dll; in .net reflector all assemblies load fine with no dependency errors. however the azure instance wants to load the old version of Microsoft.Data.OData, Version=5.6.4.0. I have all assembly bindings in place.

any idea how can I continue this investigation? what else should I look for in understanding why the azure instance is not seeing my binding redirect?

a somewhat similar problem reported here but with no answer to the kind of problem I am facing: Could not load file or assembly Microsoft.Data.OData Version=5.2.0.0 error in Azure Cloud Worker Role using Table Storage

EDIT: right now I can't even RDP anymore, all I can see is the diagnostic summary and there I can see the same error as above.

So indeed it seems like the bind redirect is ignored fully... or only for this assembly?...
can you please give me some advise how should I investigate further? I do not have access to the azure instance (I might be able to access it later... I was able to do it today at some point)

thank you very much

**Comment by oviwankenobi** [comment] 2016-03-31 20:25
and to answer my question: pfeeewww. because the webrole lives in two processes (see this
http://dzimchuk.net/post/be-aware-of-web-role-host-process) any of the binding redirects defined were not affecting the webrole.cs code but only the web app code. doh!
so... I have two options: either move all the code from webrole.cs to web app code or create special/separate binding redirects for webrole.cs
