### ISSUE TITLE
Empty string in CloudBlockBlob metadata causes CPU leak.

### ISSUE THREAD

**Issue by ansario** [Azure/azure-storage-net#592] opened 2017-12-19 19:11 UTC
The Azure Storage Rest API allows `PUT`ing empty string values in the metadata of a CloudBlockBlob by setting the optional request header x-ms-meta-name to "". The C# nuget package (8.7.0) does not return when calling the `.ListBlobs()` method on a CloudBlobDirectory when one of the CloudBlockBlobs in the directory has a few, but not all, metadata values set to empty string. On each subsequent request, CPU increases by about 10%.

![image001](https://user-images.githubusercontent.com/7139741/34174098-c0c3ec5a-e4c5-11e7-98b7-6205c6d6703b.png)

# Steps to reproduce:

1. Create `CloudBlockBlob` with several metadata Keys + non empty string values via the REST API.
2. Add one additional metadata key with an empty string value via the REST API.
3. Using C# 8.7.0 nuget package, call .`ListBlobs()` on parent `CloudBlobDirectory` of the `CloudBlockBlob.`
4. Observe CPU spike and infinte hang.

**Comment by kfarmer-msft** [comment] 2018-10-30 23:57
@ansario Does this still repro for you under 9.3.2 or 9.4.0?

**Comment by seanmcc-msft** [comment] 2019-03-14 21:36
Duplicate of https://github.com/Azure/azure-storage-net/issues/828

**Closed by seanmcc-msft** 2019-03-14 21:36 UTC
