### ISSUE TITLE
CloudTable ExecuteQuery does not exist 

### ISSUE THREAD

**Issue by oxxa** [Azure/azure-storage-net#684] opened 2018-05-15 14:01 UTC
When trying to use this from a Netstandard 2.0 lib I have the problem that the ExecuteQuery method does not exist on CloudTable.  From a quick look this seems to be because it is being defd out here
 https://github.com/Azure/azure-storage-net/blob/afc5c6d99a805fb4165631ab5cfd139238b00e71/Lib/ClassLibraryCommon/Table/CloudTable.cs#L267
As the target (  azure-storage-net/Lib/Portable/Microsoft.WindowsAzure.Storage.csproj ) does not define a SYNC constant the code does not get included in the nuget package.  Is this intentional?

**Comment by oxxa** [comment] 2018-05-15 14:19
Note I can see a 'ExecuteQuerySegmentedAsync' method exposed but cannot find documentation on its use.  I can find the same name mentioned in this [quickstart ](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-dotnet#retrieve-entities-in-pages-asynchronously) , but this raises another question, should we not use this library and use instead Microsoft.Azure.CosmosDB.Table nuget package even for 'ordinary' (non-cosmos) Azure Storage Tables?  And just use this for blobs/files/queues?

**Comment by erbaker** [comment] 2018-05-15 15:26
This issue (Originally posted to the wrong repo) seems to be identical; https://github.com/Azure/azure-sdk-for-net/issues/2840

I just noticed this as well; both overloads are marked as internal, yet documentation on MSDN clearly shows CloudTable.ExecuteQuery as public virtual. https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table.cloudtable.executequery?view=azure-dotnet

**Comment by MisinformedDNA** [comment] 2018-05-15 21:09
And the documentation [says](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-dotnet#retrieve-all-entities-in-a-partition) to use it.

I've tried WindowsAzure.Storage 9.1.1 and Microsoft.Azure.CosmosDB.Table 1.1.2 (again [per the instructions](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-dotnet#prerequisites)).

Targeting .NET Core 2.0.

**Comment by mirobers** [comment] 2018-05-16 07:10
The netstandard 2.0 target prefers to resolve to the netstandard 1.3 library, which is async-only. If you use the .NET Framework target instead, you will get access to the sync methods.

Here's a [sample using async queries](https://github.com/Azure-Samples/storage-table-dotnet-getting-started/blob/master/TableStorage/AdvancedSamples.cs#L410) for reference.

Note that the future of the table service is the Microsoft.Azure.CosmosDB.Table library; we do not have further enhancements to Table support planned for this repo.

**Comment by oxxa** [comment] 2018-05-16 15:40
Ok thanks for that.  I'll close this but perhaps this could be noted in the Api [docs ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.windowsazure.storage.table?view=azure-dotnet) or the README as this project is where most developers will head to I think assuming this is the one library to rule them all for Azure storage access.

**Comment by MisinformedDNA** [comment] 2018-05-16 15:45
But this error also occurs in the Microsoft.Azure.CosmosDB.Table library! We should keep this open until a suitable replacement issue is filed and linked.

**Comment by lordcheeto** [comment] 2018-05-17 15:52
Just wanted to report that I also ran into this unexpected behavior. Can verify that `ExecuteQuerySegmentedAsync` is working.

**Comment by oxxa** [comment] 2018-05-17 16:17
Hi @MisinformedDNA  Microsoft.Azure.CosmosDB.Table worked for me from within a Netstandard2.0 lib.  Interested to hear the error you are getting in case I run into it.

**Comment by MisinformedDNA** [comment] 2018-05-17 17:37
Targetting .NET Core, `ExecuteQuery` does not exist (with either package referenced above).

**Comment by erezvani1529** [comment] 2018-05-31 22:03
The WindowsAzure.Storage packages for Netstandard targets <= 1.3 , do not support Sync methods. Please use Async equivalent APIs instead.

CosmosDB has planned support for Netstandard targets > 1.3, Please email the team at: `askcosmosdbtableapi@microsoft.com` for more information.

Thanks!

**Closed by erezvani1529** 2018-05-31 22:03 UTC

**Comment by moosebay** [comment] 2019-07-08 21:35
> Note I can see a 'ExecuteQuerySegmentedAsync' method exposed but cannot find documentation on its use. I can find the same name mentioned in this [quickstart ](https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-how-to-use-dotnet#retrieve-entities-in-pages-asynchronously) , but this raises another question, should we not use this library and use instead Microsoft.Azure.CosmosDB.Table nuget package even for 'ordinary' (non-cosmos) Azure Storage Tables? And just use this for blobs/files/queues?

just pass to continuation key if you are not paginating:
`
var query = new TableQuery<Email>().Where(TableQuery.GenerateFilterCondition("PartitionKey", QueryComparisons.Equal, 'Smith'));
await cloudTable.ExecuteQuerySegmentedAsync(query, null);
`
