### ISSUE TITLE
Regression on Xamarin with the 8.0 release

### ISSUE THREAD

**Issue by migueldeicaza** [Azure/azure-storage-net#385] opened 2016-12-29 01:57 UTC
A customer reach out to let me know that WindowsAzure.Storage was throwing an "NotImplementedMethod" exception on Android when following the steps in these web pages:

https://docs.microsoft.com/en-us/azure/storage/storage-xamarin-blob-storage
 
https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-blob-storage
 
The customer tracked down this to be a regression that was introduced with the 8.0 release of the NuGet package.   Downgrading to 7.2.1 fixes the problem for them.

The repro test case is following the samples on the above two links.

**Comment by erezvani1529** [comment] 2016-12-29 04:57
Hi @migueldeicaza,

Thanks for bringing up the reported issue. Following the [Xamarin Storage Document ](https://docs.microsoft.com/en-us/azure/storage/storage-xamarin-blob-storage) which uses a Native Shared app as a template, I was not able to reproduce the issue.
Would you please if possible redirect the customer to this github issue if they are using the shared code approach? 

Azure Storage Client has supported Native Shared, Xamarin.Forms Shared, Xamarin.Android, and Xamarin.iOS. With 8.0 release we have added support for Portable projects through a netstandard1.0 facade (using the bait and switch technique). The [App Services Document](https://docs.microsoft.com/en-us/azure/app-service-mobile/app-service-mobile-xamarin-forms-blob-storage) yet need to be updated, however, as stated [here](https://github.com/Azure/azure-storage-net#netstandard10-façade), the correct implementation assembly will be picked when the package is referenced by the project.json file. 

It would be great if we could directly work with the reporting customer to get more details on which project type they are using and help them as we understand their exact scenario.

Thanks again!

**Comment by erezvani1529** [comment] 2017-01-11 04:17
Closing as this issue is being tracked in #387 .

**Closed by erezvani1529** 2017-01-11 04:17 UTC
