### ISSUE TITLE
Calling DeleteAsync or DeleteIfExistsAsync on table throwing error

### ISSUE THREAD

**Issue by ChrisRisner** [Azure/azure-storage-net#437] opened 2017-04-06 05:52 UTC
I'm trying to use the Azure Storage .NET SDK to delete a table in my storage account by calling either DeleteAsync or DeleteIfExistsAsync and both of them lead to this error message occurring:

Microsoft.WindowsAzure.Storage.StorageException: One of the identified items was in an invalid format. ---> System.FormatException: One of the identified items was in an invalid format.
  at System.Net.Http.Headers.HttpHeaders.AddInternal (System.String name, System.Collections.Generic.IEnumerable`1[T] values, System.Net.Http.Headers.HeaderInfo headerInfo, System.Boolean ignoreInvalid) [0x0004c] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/System.Net.Http/System.Net.Http.Headers/HttpHeaders.cs:196 
  at System.Net.Http.Headers.HttpHeaders.Add (System.String name, System.Collections.Generic.IEnumerable`1[T] values) [0x00011] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/System.Net.Http/System.Net.Http.Headers/HttpHeaders.cs:171 
  at System.Net.Http.Headers.HttpHeaders.Add (System.String name, System.String value) [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/System.Net.Http/System.Net.Http.Headers/HttpHeaders.cs:163 
  at Microsoft.WindowsAzure.Storage.Table.Protocol.TableOperationHttpRequestMessageFactory.BuildRequestForTableOperation[T] (Microsoft.WindowsAzure.Storage.Core.Executor.RESTCommand`1[T] cmd, System.Uri uri, Microsoft.WindowsAzure.Storage.Core.UriQueryBuilder builder, System.Nullable`1[T] timeout, Microsoft.WindowsAzure.Storage.Table.TableOperation operation, Microsoft.WindowsAzure.Storage.Table.CloudTableClient client, System.Net.Http.HttpContent content, Microsoft.WindowsAzure.Storage.OperationContext ctx, Microsoft.WindowsAzure.Storage.Table.TablePayloadFormat payloadFormat, Microsoft.WindowsAzure.Storage.Core.Auth.ICanonicalizer canonicalizer, Microsoft.WindowsAzure.Storage.Auth.StorageCredentials credentials) [0x000af] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Table\Protocol\TableOperationHttpRequestFactory.cs:78 
  at Microsoft.WindowsAzure.Storage.Table.TableOperation+<>c__DisplayClass64_0.<DeleteImpl>b__0 (Microsoft.WindowsAzure.Storage.Core.Executor.RESTCommand`1[T] cmd, System.Uri uri, Microsoft.WindowsAzure.Storage.Core.UriQueryBuilder builder, System.Net.Http.HttpContent cnt, System.Nullable`1[T] serverTimeout, Microsoft.WindowsAzure.Storage.OperationContext ctx) [0x00000] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Table\TableOperation.cs:129 
  at Microsoft.WindowsAzure.Storage.Core.Executor.Executor+<ExecuteAsyncInternal>d__4`1[T].MoveNext () [0x001b5] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:91 
   --- End of inner exception stack trace ---
  at Microsoft.WindowsAzure.Storage.Core.Executor.Executor+<ExecuteAsyncInternal>d__4`1[T].MoveNext () [0x002dc] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Core\Executor\Executor.cs:124 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:143 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00047] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in /Users/builder/data/lanes/4009/3a62f1ea/source/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113 
  at Microsoft.WindowsAzure.Storage.Table.CloudTable+<>c__DisplayClass47_0+<<DeleteIfExistsAsync>b__0>d.MoveNext () [0x00100] in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\WindowsRuntime\Table\CloudTable.cs:398 
--- End of stack trace from previous location where exception was thrown ---

**Comment by pemari-msft** [comment] 2017-04-06 15:54
Hi Chris -- are you using .NET core for this? Is this reproable / consistent? We don't see this in our tests, and the delete API doesn't add any other headers than in other apis, really. If you could help us figure out which header is throwing, I can try to figure out what's wrong with it.

**Comment by ChrisRisner** [comment] 2017-04-07 18:47
I'm building out a Xamarin application and using version 8.1.1 of the WindowsAzure.Storage Nuget package.  I can reproduce this every time I try to call delete on an existing table.  Any thoughts on how I might figure out what header is causing the issue?

I don't believe I'm doing anything that would affect the headers as I'm able to do this and trigger the error:
var table = tableServiceClient.GetTableReference(tableName);
bool deleted = await table.DeleteIfExistsAsync();

**Comment by erezvani1529** [comment] 2017-04-11 22:20
Hi @ChrisRisner,

Thanks for reporting this issue. The header that is causing the problem is the empty "If-Match" header that the storage client is adding internally. 
This header is ignored in case of NetCore(which we run our tests on). However, looks like Mono [throws ](https://github.com/mono/mono/blob/master/mcs/class/System.Net.Http/System.Net.Http.Headers/HttpHeaders.cs#L190) if the value is null. In terms of reporting which header is causing the problem, unfortunately there is nothing much we can do but I see an [open PR](https://github.com/mono/mono/pull/4058) discussion on how to improve the logic on Mono. 

I have a fix for this which should be out with our upcoming release.

Thanks,
Elham

**Comment by ChrisRisner** [comment] 2017-04-12 16:55
@erezvani1529 do you have an ETA on when that release to NuGet will be?

**Comment by erezvani1529** [comment] 2017-04-13 17:13
Hi @ChrisRisner,

Sure. The release is scheduled to happen by EoM (most likely sooner).

Thanks,
Elham

**Comment by erezvani1529** [comment] 2017-07-18 22:52
Hi @ChrisRisner,

This issue is fixed in [8.2](https://www.nuget.org/packages/WindowsAzure.Storage) package. Thanks again for reporting!

**Closed by erezvani1529** 2017-07-18 22:52 UTC
Labels: bug
