### ISSUE TITLE
Table Query LINQ is not supported in .NET Core.

### ISSUE THREAD

**Issue by takekazuomi** [Azure/azure-storage-net#491] opened 2017-07-07 07:12 UTC
Current TableQuery Provider is not included if NETCORE is defined.
https://github.com/Azure/azure-storage-net/blob/dev/Lib/Common/Table/TableQueryProvider.cs#L18

Do you have any technical problem. Or some human resource limitation?

Usualy I use TableQuery Provider. It more simple and clear than TableQuery<T> ways.

In Premium Storage (preview), We can use secondary index. It means we will be use more complex where clause.

I recommend to support TableQuery Provider  in NETCORE  as well.

This is not bugs. future request.

**Comment by erezvani1529** [comment] 2017-07-12 22:57
Thanks @takekazuomi , 

We are in the process of preparing a preview package targeting Netstandard2.0 which will have the missing features in our NetCore support (caused by limitations in earlier versions of Netstandard/Netcore).  We have hit some blockers in the process as discussed in #333 but the work is in progress.

Will use this issue to track this feature request (closing #265 as duplicate).

Thanks,
Elham

**Comment by juliekoubova** [comment] 2017-10-25 11:59
Hello, any ETA on this, please?

**Comment by vdecristofaro** [comment] 2017-12-27 12:05
Hello, any update on this?

**Comment by MisinformedDNA** [comment] 2018-05-15 22:25
Looking for an update. Anything?

**Comment by robdmoore** [comment] 2018-06-07 08:47
@erezvani1529 Any update on this one?

**Comment by Maurik77** [comment] 2018-06-07 14:01
Any news or forecast?

**Comment by guitarrapc** [comment] 2018-08-28 04:58
Any update?

**Comment by ginomessmer** [comment] 2018-11-15 15:29
+1. Any updates?

**Comment by michaelkruglos** [comment] 2018-11-22 09:00
What is the status of this issue? Can we count on it being implemented in the future?

**Comment by ManfredLange** [comment] 2019-01-05 00:53
In July 2017 @erezvani1529 wrote that they are working on this for target `netstandard2.0`.

Now it's 2019 and still this issue is open......

Perhaps whoever is working on this code base should now make a call whether there is any genuine interest in making this happening. Why is it so hard to get the LINQ support ported to `netstandard2.0`?

Generally, it looks as if this whole transitioning of platforms, features, and nuget packages for Azure Table storage has been completely stuffed up. NuGet package "WindowsAzure.Storage" in version 9.3.3 still has some support for Table storage but it lacks LINQ and everything is now async (required quite some rewriting).

Version 9.4 of WindowsAzure.Storage has dropped support for table storage completely. Apparently that has been moved to the packages for CosmosDB clients which are currently in preview. I saw some a comment (on SO?) that it doesn't yet support Azure Table Storage but only tables in CosmosDB, even though the client API (from .NET's perspective, e.g. C#) are identical. A version (prerelease, beta, etc) that also supports Azure Table Storage as well is planned for January 2019.

It looks very much so that support for Azure Table storage was dropped from WindowsAzure.Storage **before** it became available in package "Microsoft.Azure.Cosmos.Table" (v0.10.0-preview as of writing). So a person who wants to target netstandard2.0 is pretty much stuffed....

I've done a lot of work with AWS recently, too. And while their API is about the same, the client side libraries are easier to use and more consistent. I cannot remember that I've been on the hunt for functionality that has been moved between packages, renamed, dropped, changed, etc to the degree that I have been doing this recently around Azure Storage. Extremely frustrating and more so, very time consuming.

**Comment by seanmcc-msft** [comment] 2019-03-06 21:08
Table support has moved to the CosmosDB NuGet package.  Please follow up there.

[https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table](url)

**Closed by seanmcc-msft** 2019-03-06 21:08 UTC

**Comment by takekazuomi** [comment] 2019-03-06 22:42
@seanmcc-msft 
This Issue is about Table Storage.
Cosmos DB and Storage are quite different prices and performance characteristics. It is not the same thing.

Will table storage be abolished in the future? Otherwise, please do not CLOSE.

**Comment by MisinformedDNA** [comment] 2019-03-06 22:55
Table Storage and Cosmos DB share the same API. The story I've been told is that Cosmos DB can simply be treated as premium Table Storage. But it's certainly a confusing story. If you look at the documentation for Azure Storage, they don't even talk about tables, which makes one worry...

**Comment by Voodu** [comment] 2019-08-16 15:32
According to https://azure.microsoft.com/pl-pl/resources/samples/azure-cosmos-db-table-dotnet-getting-started/

> Azure Cosmos DB Table API SDK from Nuget, this is now the official SDK both for Azure Cosmos DB Table API as well as for Azure Table storage
