### ISSUE TITLE
SendStream is not properly disposed as result memory never returned back to memory manger.

### ISSUE THREAD

**Issue by IlyaGrebnov** [Azure/azure-storage-net#403] opened 2017-01-31 02:03 UTC
SendStream is MultiBufferMemoryStream (created by HttpWebRequestAdapterMessage), but it never get properly disposed as result memory never returned back to memory manger.

**Comment by IlyaGrebnov** [comment] 2017-01-31 02:41
Regressed between version 4.3.0 and version 8.0.1

**Comment by IlyaGrebnov** [comment] 2017-01-31 05:01
Have not tested preview versions, but version 5.0.0 already regressed.

**Comment by erezvani1529** [comment] 2017-02-01 00:35
Hi @IlyaGrebnov,

Would you mind sharing some more information about this or how you found out about it? We do dispose SendStream when disposing ExecutionState, if that is what you are referring to.

Thanks,
Elham

**Comment by IlyaGrebnov** [comment] 2017-02-01 20:35
Here is repro program: basic stuff like create table or create entity is broken.

    public class StorageBufferManager : IBufferManager
    {
        public static StorageBufferManager Instance = new StorageBufferManager();

        public int AllocatedPoolBytes;
        public int DeallocatedPoolBytes;

        public int GetDefaultBufferSize()
        {
            return 16 * 1024;
        }

        public void ReturnBuffer(byte[] buffer)
        {
            Interlocked.Add(ref this.DeallocatedPoolBytes, buffer.Length);
        }

        public byte[] TakeBuffer(int bufferSize)
        {
            Interlocked.Add(ref this.AllocatedPoolBytes, bufferSize);
            return new byte[bufferSize];
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var account = CloudStorageAccount.DevelopmentStorageAccount;
            var tableClient = account.CreateCloudTableClient();
            var tableReference = tableClient.GetTableReference("test");

            tableClient.BufferManager = StorageBufferManager.Instance;

            tableReference.CreateIfNotExistsAsync().Wait();
            System.Console.WriteLine("{0} {1}", StorageBufferManager.Instance.AllocatedPoolBytes, StorageBufferManager.Instance.DeallocatedPoolBytes);

            var entity = new DynamicTableEntity("test", "test");
            var tableResult = tableReference.ExecuteAsync(TableOperation.InsertOrReplace(entity)).Result;
            System.Console.WriteLine("{0} {1}", StorageBufferManager.Instance.AllocatedPoolBytes, StorageBufferManager.Instance.DeallocatedPoolBytes);
        }
    }

**Comment by erezvani1529** [comment] 2017-02-03 00:47
Thanks a @IlyaGrebnov for reporting this issue.

This is indeed a regression in 5.0 release where we modified the dispose logic but missed applying it to table operations. I have fixed this which will be released with 8.1 (our next release). Will update with respective PR.

-Elham

**Comment by IlyaGrebnov** [comment] 2017-02-04 00:08
I updated my program in a way even storage lib 4.3 is broken.  Could you please review it and make sure 8.1 works. Thanks.

**Comment by erezvani1529** [comment] 2017-02-09 00:11
Sure. thanks for the update. What I have fixed was specifically introduced in 5.0 and only for table operations. I will for sure make sure this is fixed in all cases. 

One more point, the 8.1 milestone has been renamed to 8.2 (with the same release timeline) since we are planning for an early release(8.1) next week to update our OData packages to the recently released netstandard friendly version.

**Comment by zsybupt** [comment] 2017-06-14 03:20
when this bug will be fixed? I find my asp.net application create a lot of bytes when execute query, the sdk version is 8.1.1.0,Thanks

**Comment by erezvani1529** [comment] 2017-06-14 17:48
Hi @zsybupt,

This issue has been fixed for TableOperations. Please upgrade to [8.1.4](https://www.nuget.org/packages/WindowsAzure.Storage/8.1.4) to get the fix. We are keeping this issue open since there are some other cases (not Table Operation Specific) to be fixed as well which require a more involved change in the library.

Thanks,
Elham

**Comment by zsybupt** [comment] 2017-06-15 06:50
Thanks

**Closed** 2018-08-14 00:10 UTC
Labels: bug
