### ISSUE TITLE
Table query LINQ Where sensitive to property order?

### ISSUE THREAD

**Issue by kitsu** [Azure/azure-storage-net#482] opened 2017-06-13 23:18 UTC
I just had an issue trying to filter a table by dates. My entities have a Start and an End, and in my query I was trying to select entities that are started, but not ended. I tried with the following obvious code:

``` CSharp
    var query = _table.CreateQuery<MyEntity>()
        .Where(m => m.Start <= now && now < m.End);
```

This produced no results though, despite my test data being tailored to succeed. After much testing (including finding that omitting the end check returned results) I discovered *this* does work:

``` CSharp
    var query = _table.CreateQuery<MyEntity>()
        .Where(m => m.Start <= now && m.End > now);
```

This is unexpected because the comparisons are equivalent. My guess is when encoding LINQ as a rest call you are making some (invalid) assumptions about the order of comparisons...

VS2015, Storage 8.1.4, .NET Framework 4.5.2 (i.e. not Core).

**Comment by erezvani1529** [comment] 2017-06-16 22:41
Hi @kitsu,

I was not able to reproduce this issue with the steps you described. Would you be able to take a fiddler trace to show what your query looks like? This will be help us identify what is happening. 

Thanks,
Elham

**Comment by kitsu** [comment] 2017-06-19 22:01
Here is the failing query from the `WebForms` tab:

    $filter: (Start le datetime'2017-06-19T21:48:46.339453Z') and (datetime'2017-06-19T21:48:46.339453Z' lt End)

And the working version:

    $filter: (Start le datetime'2017-06-19T21:48:46.339453Z') and (End gt datetime'2017-06-19T21:48:46.339453Z')

Since the queries seem reasonable I assume this is an upstream issue? Maybe specific to the Storage Emulator?

**Comment by erezvani1529** [comment] 2017-06-23 18:00
Hi @kitsu,

Yes, I confirmed this is an emulator issue. We will fix this in the next release of the emulator and update this issue.

Thanks again for reporting this,
Elham

**Comment by kfarmer-msft** [comment] 2019-03-11 21:31
As you may have heard, we are moving to a completely new emulator.  Please try it, and see if it resolves the issue you encountered.

https://github.com/azure/azurite

**Closed by kfarmer-msft** 2019-03-11 21:31 UTC
Labels: Emulator
