### ISSUE TITLE
System.ArgumentOutOfRangeException when uploading blob from stream 

### ISSUE THREAD

**Issue by Yonisha** [Azure/azure-storage-net#555] opened 2017-10-22 15:51 UTC
Microsoft.WindowsAzure.Storage.StorageException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Core.MultiBufferMemoryStream.EndRead(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\Core\MultiBufferMemoryStream.cs:line 217
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1.<StartCopyStreamAsyncHelper>d__8.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncStreamCopier.cs:line 257
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncStreamCopier`1.<StartCopyStreamAsync>d__4.MoveNext() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncStreamCopier.cs:line 222
   --- End of inner exception stack trace ---
   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End() in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\StorageAsyncResult.cs:line 77
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.EndUploadFromStream(IAsyncResult asyncResult) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Blob\CloudBlockBlob.cs:line 790
   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass4.<CreateCallbackVoid>b__3(IAsyncResult ar) in c:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\ClassLibraryCommon\Core\Util\AsyncExtensions.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
.....
Request Information
RequestID:
RequestDate:
StatusMessage:

I'm using Azure Storage 8.5 and apparently this bug has been solved in 8.1.4 (https://github.com/Azure/azure-storage-net/issues/471).

**Comment by erezvani1529** [comment] 2017-10-23 05:26
Hi @Yonisha ,

Thanks for reporting this issue. The stack trace shows a different root here and we will investigate and get back to you soon.

**Comment by erezvani1529** [comment] 2017-11-06 21:06
Hi Yonisha,

We have investigated and have a fix for this issue but due to the nature of the issue it is very difficult to reproduce locally. Is there a possibility that you could share a dump with us so that we can confirm the root cause? (if yes please share with `ascl at microsoft dot com`)

Thanks,
Elham

**Comment by Yonisha** [comment] 2017-11-26 09:03
Hi @erezvani1529,

While at the time of reporting this issue was very often, now it is very rare.
I'll share a dump in case I have one.

Thanks.

**Comment by erezvani1529** [comment] 2018-02-12 22:41
Hi Yonisha,

Please try v8.7 which should have solved this issue as well. Please do not hesitate to re-open if you see any other instances.

Thanks!

**Closed by erezvani1529** 2018-02-12 22:41 UTC
