### ISSUE TITLE
Including Error code in StorageException or RequestResult

### ISSUE THREAD

**Issue by lsarni** [Azure/azure-storage-net#389] opened 2017-01-10 13:09 UTC
Would it be possible to include the "error code" in either the StorageException or the RequestResult (inside the exception)? [Here](https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/blob-service-error-codes) there is a list of possible errors and I guess it comes as part of the http response.
I think it would be really useful, more than the httpcode and message (which works to display the error but not for handling it in the code itself).

Or is there already a way of getting this that I haven't find?
I have tried with `ex.RequestInformation?.ExtendedErrorInformation?.ErrorCode` but `ExtendedErrorInformation` comes null so it is of no use.

**Comment by pemari-msft** [comment] 2017-01-10 16:04
If your ExtendedErrorInformation is null, then you're likely missing a dependency. We made a fix for this in 8.0, can you try upgrading your library? Otherwise, please make sure your dependencies are correctly placed? Then yes,  `ex.RequestInformation?.ExtendedErrorInformation?` will have the info you're looking for.

**Closed by pemari-msft** 2017-01-10 16:04 UTC

**Comment by lsarni** [comment] 2017-01-10 16:27
@pemari-msft  I upgraded the library but it's still null. Which dependency may be the one causing this?

**Comment by pemari-msft** [comment] 2017-01-10 16:29
Usually it's due to a missing OData dependency. But starting in 8.0, that shouldn't be the cause. Can you give more information as to how the request is failing, etc, to see if we can figure out what's happening? Or does it repro in a standalone console app?

**Comment by lsarni** [comment] 2017-01-10 16:46
I added OData but it's still null.

 The request is failing when trying to download an object that isn't in the bucket:

> The remote server returned an error: (404) Not Found.
>  at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
>    at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.DownloadToStream(Stream target, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
>    at Microsoft.WindowsAzure.Storage.Blob.CloudBlob.DownloadToFile(String path, FileMode mode, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
> 
The HttpStatusMessage is :
> The specified blob does not exist.

I will check if it's reproducible in a standalone console app.

**Comment by pemari-msft** [comment] 2017-01-10 16:58
How are you installing the client library into your project? What platform is your project targeting? Do you have all the dependencies correctly placed?

**Comment by lsarni** [comment] 2017-01-10 17:04
I was missing Microsoft.Data.Services.Client, by adding just that one (OData didn't helped) the problem was fixed.
Thanks!
